version: '2'
services:
  apache:
       build:
               context: .
               dockerfile: Dockerfile_apache2
       container_name: apache
       depends_on:
         - db
         - nginx
       ports:
         - 9000:9000
  
  nginx:
       build:
               context: .
               dockerfile: Dockerfile_nginx_final_updated 
       container_name: nginx 
       ports:
         - 80:80
  
  db:
          build:
                  context: ./database
                  dockerfile: Dockerfile_db
          container_name: db 
          command: --default-authentication-plugin=mysql_native_password
          restart: always
          environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_USER: edureka
            MYSQL_PASSWORD: admin
          ports:
           - 6033:3306

