FROM nginx:latest 
#RUN rm -f /etc/nginx/sites-available/default
RUN apt-get update && apt-get install php-fpm curl nano -y
COPY . /var/www/html
COPY default /etc/nginx/sites-available/default
COPY default.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
